#!/bin/bash -ex
# ------------------------------------------------------------------
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
# ------------------------------------------------------------------

set -eo pipefail # be more strict about non-zero exits and unset var substitutions

usage() {
  cat << EOM
Usage: ci_run_pipeline.sh   [ --work-dir <workdir> ]
                            [ --tmp-dir <TMPDIR> ]
                            [ --hf-home <path to cache huggingface download> ]
                            [ --qeff-home <path to cache onnx and qpc files generated by QEfficient> ]
                            [ --host <Host IP for online tests> ]
                            [ --port <Port for online tests> ]
                            [ --mode <aot|pyt|all> ]
--work-dir  set this path to create workspace required.
--hf-home   set this path to cache huggingface download.
--tmp-dir   set this path to cache python workspace.
--qeff-home set this path to cache onnx and qpc files generated by QEfficient.
--host      (Optional) set this to run the online tests on a particular server. Default: localhost
--port      (Optional) set this to run the online tests on a particular server. Default: 8080
--mode      (Optional) inference mode to install and test. Default: aot
EOM
}

VLLM_DIR=$(dirname "$(dirname "$(readlink -f "$0")")")
ROOT_DIR=$(dirname "$(readlink -f "${VLLM_DIR}")")
HOST="localhost"
PORT="8080"
modes="aot"

export HF_HOME=${ROOT_DIR}/model
export QEFF_HOME=${ROOT_DIR}/qpcs
export OUTLINES_CACHE_DIR=${VLLM_DIR}

while [ $# -gt 0 ]; do
    if [ z"$1" == "z-h" ] || [ z"$1" == "z--help" ]; then
        usage
        exit 1
    elif [ z"$1" == "z--hf-home" ]; then
        export HF_HOME=$2
        shift 2
    elif [ z"$1" == "z--tmp-dir" ]; then
        export TMPDIR=$2
        shift 2
    elif [ z"$1" == "z--qeff-home" ]; then
        export QEFF_HOME=$2
        shift 2
    elif [ z"$1" == "z--work-dir" ]; then
        export ROOT_DIR=$2
        shift 2
    elif [ z"$1" == "z--host" ]; then
        HOST=$2
        shift 2
    elif [ z"$1" == "z--port" ]; then
        PORT=$2
        shift 2
    elif [ z"$1" == "z--mode" ]; then
        case "$2" in
            aot|pyt)
                modes="$2"
                ;;
            all)
                modes="aot pyt"
                ;;
            *)
                echo "Invalid mode: $2. Expected aot, pyt, or all."
                usage
                exit 1
                ;;
        esac
        shift 2
    else
        echo "Unused/invalid option: " "$1"
        usage
        exit 1
    fi
done

echo "Creating Directories"
mkdir -p "${HF_HOME}" "${QEFF_HOME}" "${TMPDIR}"
chmod 777 "${TMPDIR}"

echo "HF_HOME            : ${HF_HOME}"
echo "QEFF_HOME          : ${QEFF_HOME}"
echo "OUTLINES_CACHE_DIR : ${OUTLINES_CACHE_DIR}"
echo "ROOT_DIR           : ${ROOT_DIR}"
echo "TMPDIR             : ${TMPDIR}"

echo #set vllm env variables

export VLLM_BUILD_WITH_QAIC=True
export PROMETHEUS_MULTIPROC_DIR=${TMPDIR}

function create_python_venv() {
        mode_env_dir="env_$1"
        mkdir -p ./"${mode_env_dir}" && cd ./"${mode_env_dir}"
        sudo apt install -y python3.12-venv
        python3.12 -m venv .
        source bin/activate
        python3 -m pip install --upgrade build --trusted-host "devpi.qualcomm.com"
        cd ..
}

function install_vllm_plugin() {
        mode="$1"
        cd "${VLLM_DIR}"
        ./scripts/install.sh "$mode"
        # install test dependencies (single source of truth: requirements/test.txt)
        pip3 install -r requirements/test.txt
}

function execute_tests() {
    mode="$1"
    cd "${VLLM_DIR}"/ci_scripts
    # shellcheck disable=SC1090
    source ./ci_fasttest_qaic_"${mode}".sh --host "${HOST}" --port "${PORT}"
    cd "${VLLM_DIR}"
}
for mode in $modes
do
    echo "running CI pipeline for $mode inference mode"
    create_python_venv "$mode"
    install_vllm_plugin "$mode"
    execute_tests "$mode"
done
