#!/usr/bin/env python3
# ------------------------------------------------------------------
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
# ------------------------------------------------------------------
#
# Convert a Claude-style agent definition (Markdown + YAML frontmatter) into a
# Codex standalone custom-agent file (TOML).
#
# Claude reads `.claude/agents/<name>.md` with `name`/`description` frontmatter and
# the body as instructions. Codex reads `.codex/agents/<name>.toml` with `name`,
# `description`, and `developer_instructions` keys. The content is portable; only
# the container differs, so we generate the TOML rather than maintain two copies.
#
# Usage: md_agent_to_codex_toml.py <in.md> <out.toml>

import sys
from pathlib import Path


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter, body). Supports only the scalar and folded-scalar
    (`>`) forms actually used by the agent definitions in skills_studio/."""
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    _, raw, body = text.split("---\n", 2)

    fields: dict[str, list[str]] = {}
    key = None
    for line in raw.splitlines():
        if not line.strip():
            continue
        if not line.startswith((" ", "\t")) and ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip()
            # `>` / `|` introduce a multi-line scalar: the value is the
            # following indented block, not the marker itself.
            fields[key] = [] if value in (">", "|", ">-", "|-") else [value]
        elif key is not None:
            fields[key].append(line.strip())
    return {k: " ".join(v).strip() for k, v in fields.items()}, body.lstrip("\n")


def to_toml(fields: dict[str, str], body: str) -> str:
    for required in ("name", "description"):
        if not fields.get(required):
            raise ValueError(f"frontmatter is missing required key '{required}'")

    def basic_string(value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    # A multi-line basic string cannot contain an unescaped `"""`, and a trailing
    # `"` would run into the closing delimiter.
    instructions = body.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        "# Generated by skills_studio/tools/md_agent_to_codex_toml.py — do not edit.\n"
        "# Source of truth: skills_studio/agents/*.md (edit that, then `make codex`).\n"
        f"name = {basic_string(fields['name'])}\n"
        f"description = {basic_string(fields['description'])}\n"
        f'developer_instructions = """\n{instructions.rstrip()}\n"""\n'
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {Path(argv[0]).name} <in.md> <out.toml>", file=sys.stderr)
        return 2
    src, dst = Path(argv[1]), Path(argv[2])
    try:
        fields, body = split_frontmatter(src.read_text(encoding="utf-8"))
        toml = to_toml(fields, body)
    except ValueError as exc:
        print(f"ERROR: {src}: {exc}", file=sys.stderr)
        return 1
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(toml, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
